version: '3.8'

services:
  backend:
    build: ./backend
    container_name: chestxray-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/models
    environment:
      - MODEL_PATH=models/pneumonia_model.h5
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: chestxray-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
